# erpnext
FROM ubuntu:22.04
LABEL author=guinan.lin

# 设定参数
ENV MARIADB_ROOT_PASSWORD=Pass1234
ENV ADMIN_PASSWORD=admin

# 定义构建参数 ARG
ARG GIT_AUTH_TOKEN_INNER

# 在 Dockerfile 中使用构建参数
ENV GIT_AUTH_TOKEN_INNER=$GIT_AUTH_TOKEN

# ENV GIT_AUTH_TOKEN= $GIT_AUTH_TOKEN

# mount授权token
# RUN --mount=type=secret,id=GIT_AUTH_TOKEN \
#   export GIT_AUTH_TOKEN=$(cat /run/secrets/GIT_AUTH_TOKEN)

# ENV GIT_AUTH_TOKEN=${GIT_AUTH_TOKEN}


# cat /run/secrets/GIT_AUTH_TOKEN

# 拷贝基础软件安装脚本
COPY ./erpnext14/installdata /installdata

# 运行基础软件安装脚本。
RUN /bin/bash -c "chmod -R 777 /installdata/* && /installdata/install-erpnext14-ubuntu22.04-bubbles.sh -qd"

# 切换用户
USER frappe
WORKDIR /home/frappe/frappe-bench

ENV ERPNEXTCN_PATH=https://guinanlin:${GIT_AUTH_TOKEN_INNER}@github.com/guinanlin/erpnextcn.git
ENV SITE_ANME=site1.local

# 安装中国本地化软件
RUN bench get-app ${ERPNEXTCN_PATH}
RUN bench --site ${SITE_ANME} install-app erpnextcn

EXPOSE 3306 80

VOLUME /home/frappe/frappe-bench/sites
VOLUME /var/lib/mysql

STOPSIGNAL SIGTERM

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["sudo /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"]
