name: ERPNext14-bubbles
on:
  workflow_dispatch: #github页面手动触发
  push:
    tags:
      - "v*.*"
env:
  IMAGE_NAME: erpnext14 #这是您的镜像名
jobs:
  get-private-git:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use GitHub Token
      run: |
        # 使用 GH_TOKEN 环境变量来设置 git 的身份验证信息
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git config --global credential.helper store

        # 使用访问令牌来访问私有仓库
        git clone https://github.com/guinanlin/erpnextcn.git

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  get-tags:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    outputs:
      tags: ${{ steps.set-output-id.outputs.tags }}
    steps:
      - uses: actions/checkout@v2.5.0
      - name: set-output
        id: set-output-id
        run: |
          VERSION=basic
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo ::set-output name=tags::${VERSION}          
  push-docker-hub:
    needs: get-tags
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./erpnext14/Dockerfile-bubbles
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.get-tags.outputs.tags }}
# ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest         
