name: 测试密钥和变量
on:
  workflow_dispatch: #github页面手动触1发

jobs:
  get-tags:
    runs-on: ubuntu-20.04
    env:
      TZ: Asia/Shanghai
    outputs:
      tags: ${{ steps.set-output-id.outputs.tags }}
    steps:
      - name: set-output
        id: set-output-id
        run: |
          VERSION=bubbles
          echo "版本号：${{ vars.APP_ID }}"     